### ISSUE TITLE
final fantasy 8 disk 3 on ios 

### ISSUE THREAD

**Issue by asbel123** [notaz/pcsx_rearmed#24]
i up too the  lunar cry videos after that my chacter not moving i press button doesnt i got the save state with me file its call ff8 state1 disk 3 and srm file on win rar ok test it out please fix it new version for iphone.

i give u my rar file and what ur email address notaz i sent it to u my gmail account beacuse i cant upload win rar file on github.

**Comment by Ch0kehold** [comment]
I would like to bump this issue as well.

Playing on iOS with the latest build of RetroArch that Cydia provides me with.
My savestates can be found here: http://animesource.info/choke/upload/prx-ff8c.rar
iPhone 5S, playing with the interpreter core as the others just crash.

If this is a handheld device issue, is it theoretically possible as a workaround to transfer either of the .srm or .state files to say, a Windows PC, and play on through the failure point, save anew and transfer the files back onto the phone?

Please comment back, I'll gladly help with anything.

**Comment by notaz** [comment]
I've looked at this issue and it's not easy to fix because of how PCSX is designed.

I think somebody reported that forcing PAL region allows to get past that point.

**Comment by Ch0kehold** [comment]
That actually helped. Running the NTSC game on forced PAL sped everything up, so that I could get past the point where it previously failed.
Getting the speed back to regular NTSC speed however called for a reboot of the emulator app, just setting it back to auto didn't work.

I can't speak for trying to force NTSC specifically back from PAL, only from PAL to auto, which did not work.

Either way, this seems to be a viable workaround, until, if ever, a fix is made.
Thank you so much for the help :)

**Comment by Rakurai** [comment]
This won't help the issue, but you also get around the issue like this.  Open up the save file in an editor like [Hyne](https://github.com/myst6re/hyne) and advance the storyline to just past that scene.  In the save slot under "Field", check the box next to value 2535 (the first Lunar Base - Passageway), then save it, rename to .srm, and load your game.  I don't think you'll even miss a line of dialog, it will be the point just after the cutscene when you regain control of Squall.

**Comment by gameblabla** [comment]
This can be closed as my PR https://github.com/notaz/pcsx_rearmed/pull/184 fixed that issue (along with other games).
