### ISSUE TITLE
Internal (HLE) BIOS breaks games

### ISSUE THREAD

**Issue by notaz** [notaz/pcsx_rearmed#6]
The Internal (HLE) BIOS implementation is incomplete and has issues, so I'll just list the most reported breaking games here in single place. To get these games working, just provide authentic PSX BIOS ROM image, model usually doesn't matter.

It is desirable to have this improved to avoid file dependency, it was also observed on slow devices that some games run faster in HLE mode. Nocash has recently released some information that may help anyone wanting to improve this:
http://nocash.emubase.de/psx-spx.htm#kernelbios
- CTR - loading hang
- Disruptor - broken memcard/crash
- Dracula X translation - loading hang/emu deadlock
- FF8 - memcards, battle crash
- Ghost in the Shell - boot
- Klonoa - game crash
- Metal Gear Solid - boot
- Metal slug - sound problems
- Misadventures of Tron Bonne - loading hang
- NFS2 - won't boot
- NFS3 - loading hang
- Policenauts - won't load
- Raystorm - emu lockup
- Ridge Racer Revolution - controls
- Road Rash - boot
- Strider - hang

**Comment by gameblabla** [comment]
I've tested a few of those games that i didn't try before and here are the games that are since fixed (at least partially) :
- Crash Team Racing (Fixed thanks to my uninitialized memory patch)
- Disruptor (Fixed since latest HLE changes)
- Raystorm (missing sounds)
- Strider (Working fine, cutscenes with voices seem to have a delay)

Games that still don't work
- FF8
The memory card issue is the same one shared by Ridge Racer 4, Ape Escape and Nuclear Strike. The real BIOS adds delays to the reads/writes but the HLE bios doesn't. Without those, it breaks games.

The battle issue is unknown... It could be related to the issue with Digimon Rumble Arena not booting
- Klonoa
The game's demo is several glitchy and it hangs upon trying to start a new game.

- Metal Gear Solid
Refuses to boot at all.

I believe the controls in Ridge Racer Revolution are fixed but i am unusre on that. The rest, i have no tried.

**Comment by notaz** [comment]
"Just" a bit more than 10 years passed and most (if not all) of these issues are fixed now. If there are still broken games left, separate issues should be opened as the causes are likely different.
